// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example.proto

#include "example.pb.h"
#include "example.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SimpleMath_method_names[] = {
  "/SimpleMath/TimesTwo",
};

std::unique_ptr< SimpleMath::Stub> SimpleMath::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SimpleMath::Stub> stub(new SimpleMath::Stub(channel, options));
  return stub;
}

SimpleMath::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TimesTwo_(SimpleMath_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SimpleMath::Stub::TimesTwo(::grpc::ClientContext* context, const ::ReqType& request, ::RespType* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ReqType, ::RespType, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TimesTwo_, context, request, response);
}

void SimpleMath::Stub::async::TimesTwo(::grpc::ClientContext* context, const ::ReqType* request, ::RespType* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ReqType, ::RespType, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TimesTwo_, context, request, response, std::move(f));
}

void SimpleMath::Stub::async::TimesTwo(::grpc::ClientContext* context, const ::ReqType* request, ::RespType* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TimesTwo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RespType>* SimpleMath::Stub::PrepareAsyncTimesTwoRaw(::grpc::ClientContext* context, const ::ReqType& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RespType, ::ReqType, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TimesTwo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RespType>* SimpleMath::Stub::AsyncTimesTwoRaw(::grpc::ClientContext* context, const ::ReqType& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTimesTwoRaw(context, request, cq);
  result->StartCall();
  return result;
}

SimpleMath::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SimpleMath_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SimpleMath::Service, ::ReqType, ::RespType, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SimpleMath::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ReqType* req,
             ::RespType* resp) {
               return service->TimesTwo(ctx, req, resp);
             }, this)));
}

SimpleMath::Service::~Service() {
}

::grpc::Status SimpleMath::Service::TimesTwo(::grpc::ServerContext* context, const ::ReqType* request, ::RespType* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


